### PR TITLE
making initial changes to update spring-boot version, ect...

### PR DESCRIPTION
**Pull request by dougj0220**

### CODE REVIEW

**Comment by dougj0220** [comment]
my bad, did not mean to intiate a PR against the main repo... Closing this PR...

**Comment by derknorton** [comment]
No worries Doug.  Hey, let me know if you are working on crypto-payment/contract related projects, I am always interested in them.  I am out of the country for a couple weeks but should be back on line in May.

Cheers,
Derk Norton
Crater Dog Technologies

**Comment by dougj0220** [comment]
Hi Derk,
If your ok with the changes I could issue another PR? I was actually planning on making more changes as well... I actually just started working for Blackhawk Network this week. So I am trying to become more familiar with the domain, and thats why I stated playing with your example project.

Doug

**Comment by derknorton** [comment]
Sure, you can do a fresh PR.  I won't be back in the US for another week so I might not get to it before then.  Also, this code is not used at Blackhawk Network, but the repositories at https://github.com/craterdog are...

**Pull request closed without merging**
